# Instead of creating two containers and create a network so they can interact with each other
# We Create A docker-compose which creates multiple containers at once with the ability to interact
services: 
  pg-database: 
    image: postgres:16 
    ports: 
      - "5432:5432" 
    volumes: 
      - ./Data:/var/lib/postgresql/data:rw 
    environment: 
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=root 
      - POSTGRES_DB=ny_taxi 
  pg-admin: 
    image: dpage/pgadmin4 
    ports: 
      - "8080:80" 
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=root 
